fix(deployment): deployment actions - try with deploy keys

diff --git a/.github/workflows/eks-deploy.yml b/.github/workflows/eks-deploy.yml
--- a/.github/workflows/eks-deploy.yml
+++ b/.github/workflows/eks-deploy.yml
@@ -54,8 +54,8 @@ jobs:
       - name: Checkout tools repo
         uses: actions/checkout@v4
         with:
-          repository: truemark/k8s-deployments
-          token: ${{ secrets.PAT }}
+          repository: d3vb0ox/k8s-deployments
+          ssh-key: ${{ secrets.K8S_DEPLOY_KEY }}
           path: k8s-deployments
 
       - name: Update image tag in values.yaml
@@ -68,8 +68,54 @@ jobs:
           git add applications/hello-world/${{ inputs.environment }}.yaml
           git commit -m "Update image tag to $IMAGE_TAG"
           git push origin main
+
+      - name: Poll application status
+        env:
+          APP_NAME: hello-world
+        run: |
+          aws eks update-kubeconfig --region us-east-2 --name ${{ vars.CLUSTER_NAME }}
+          echo "Polling application status for $APP_NAME..."
           
-      
+          INITIAL_CHECK_DONE=false
+          MAX_ATTEMPTS=30
+          ATTEMPT=0
+          
+          while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+          STATUS=$(kubectl get -n argocd application/$APP_NAME -o jsonpath='{.status.sync.status}')
+          HEALTH=$(kubectl get -n argocd application/$APP_NAME -o jsonpath='{.status.health.status}')
+          echo "$(date): Sync status: $STATUS, Health status: $HEALTH"
+        
+          # Ignore the initial Healthy/Synced state
+          if [[ "$INITIAL_CHECK_DONE" == "false" ]]; then
+          echo "Ignoring initial status: Sync=$STATUS, Health=$HEALTH"
+          if [[ "$STATUS" != "Synced" || "$HEALTH" != "Healthy" ]]; then
+          INITIAL_CHECK_DONE=true
+          fi
+          else
+          # Check for successful sync and healthy state
+          if [[ "$STATUS" == "Synced" && "$HEALTH" == "Healthy" ]]; then
+          echo "Application $APP_NAME successfully synced and healthy."
+          break
+          fi
+          fi
+        
+          # Increment the attempt counter
+          ATTEMPT=$((ATTEMPT + 1))
+          echo "Attempt $ATTEMPT/$MAX_ATTEMPTS complete. Retrying in 10 seconds..."
+        
+          # Wait for 10 seconds before polling again
+          sleep 10
+          done
+          
+          if [[ $ATTEMPT -ge $MAX_ATTEMPTS ]]; then
+          echo "Reached maximum attempts ($MAX_ATTEMPTS). Exiting with failure."
+          exit 1
+          fi
+          
+          echo "Recent events for $APP_NAME:"
+          kubectl get -n argocd events --field-selector involvedObject.name=$APP_NAME --sort-by='.metadata.creationTimestamp' -o wide | tail -n 5
+          
+
 
 #      - name: Setup Cluster Access
 #        run: |
