Updating the PROD workflow.

diff --git a/.github/workflows/prod-values-update.yml b/.github/workflows/prod-values-update.yml
--- a/.github/workflows/prod-values-update.yml
+++ b/.github/workflows/prod-values-update.yml
@@ -1,10 +1,7 @@
-name: Prod Values Update
+name: Stage Values Update
 
 on:
   push:
-    branches:
-      - main
-      - hotfix/**
     paths:
       - 'kubernetes/prod/**'
   workflow_dispatch:
@@ -14,7 +11,7 @@ permissions:
   contents: write
 
 jobs:
-  prod-values-update:
+  stage-values-update:
     name: Update Values for Prod
     runs-on: ubuntu-latest
     environment: prod
@@ -30,6 +27,10 @@ jobs:
         id: setup-environment
         run: |
           UPDATED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^kubernetes/')
+          if [[ -z "$UPDATED_FILES" ]]; then
+            echo "No files were updated. Exiting."
+            exit 1
+          fi
           echo $UPDATED_FILES > updated_files.txt
           echo "UPDATED_FILES=$(cat updated_files.txt)" >> $GITHUB_ENV
           echo "APP_NAME=hello-world" >> $GITHUB_ENV
@@ -55,24 +56,35 @@ jobs:
           path: k8s-deployments
 
       - name: Copy Updates to Deployment Repo
+        id: copy-updates
         env:
           APP_NAME: ${{ env.APP_NAME }}
           UPDATED_FILES: ${{ env.UPDATED_FILES }}
         run: |
-          cp ${{ env.UPDATED_FILES }} k8s-deployments/environments/prod/${{ env.APP_NAME }}/
+          for file in ${{ env.UPDATED_FILES }}; do
+            cp "$file" "k8s-deployments/environments/prod/${{ env.APP_NAME }}/"
+          done
+          
           cd k8s-deployments
+          git add -- "environments/prod/${{ env.APP_NAME }}/"
+          
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add environments/prod/${{ env.APP_NAME }}/$(basename ${{ env.UPDATED_FILES }})
-          git commit -m "Update deployment values for prod from ${{ env.UPDATED_FILES }}"
-          git push origin main
-
-      - name: Set Summary of Changes
-        env:
-          APP_NAME: ${{ env.APP_NAME }}
-          UPDATED_FILES: ${{ env.UPDATED_FILES }}
-        run: |
-          echo ":thumbsup: Updated values for $APP_NAME in prod from $UPDATED_FILES :thumbsup:" >> $GITHUB_STEP_SUMMARY
+          
+          if git diff-index --quiet HEAD; then
+            echo "No changes to commit."
+            echo "NO_CHANGES=true" >> $GITHUB_ENV
+            exit 1
+          else
+            git diff --staged > ../diff_output.txt
+            cat ../diff_output.txt || echo "Failed to generate diff_output.txt"
+            git commit -m "Update deployment values for prod from ${{ env.UPDATED_FILES }}"
+            git push origin main
+            if [[ $? -ne 0 ]]; then
+              echo "PUSH_FAILED=true" >> $GITHUB_ENV
+              exit 1
+            fi
+          fi
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
@@ -84,12 +96,44 @@ jobs:
         run: |
           aws eks update-kubeconfig --region us-east-2 --name ${{ vars.CLUSTER_NAME }}
 
-      - name: Install kubectl and yq
-        uses: truemark/kubectl-action@converting-to-typescript
-        with:
-          kubectl-enabled: true
+      - name: Failure Summary
+        if: env.NO_CHANGES == 'true' || env.PUSH_FAILED == 'true' || failure() && steps.copy-updates.outcome == 'failure'
+        env:
+          APP_NAME: ${{ env.APP_NAME }}
+          UPDATED_FILES: ${{ env.UPDATED_FILES }}
+        run: |
+          if [ "$NO_CHANGES" == "true" ]; then
+            echo "No changes detected. Failing the pipeline."
+            echo ":x: No changes to found for $APP_NAME in prod :x:" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [ "$PUSH_FAILED" == "true" ]; then
+            echo ":x: Git push failed for $APP_NAME in prod from $UPDATED_FILES. Details below: :x:" >> $GITHUB_STEP_SUMMARY
+            echo "### Git Push Output" >> $GITHUB_STEP_SUMMARY
+            echo "```" >> $GITHUB_STEP_SUMMARY
+            cat git_push_output.txt >> $GITHUB_STEP_SUMMARY
+            echo "```" >> $GITHUB_STEP_SUMMARY
+          fi
+
+      - name: Successful Summary
+        if: env.NO_CHANGES != 'true' && env.PUSH_FAILED != 'true'
+        env:
+          APP_NAME: ${{ env.APP_NAME }}
+          UPDATED_FILES: ${{ env.UPDATED_FILES }}
+        run: |
+          if [ -f ./diff_output.txt ]; then
+            {
+              echo '### Changes Applied:';
+              echo '';
+              echo '```diff';
+              cat ./diff_output.txt;
+              echo '```';
+            } >> $GITHUB_STEP_SUMMARY
+          else
+            echo "No changes detected in the diff output." >> $GITHUB_STEP_SUMMARY
+          fi
 
       - name: Poll application status
+        if: env.NO_CHANGES != 'true' && env.PUSH_FAILED != 'true' && steps.failure-summary.outcome != 'success'
         env:
           APP_NAME: ${{ env.APP_NAME }}
         run: |
