Still Debugging.

diff --git a/.github/workflows/stage-values-update.yml b/.github/workflows/stage-values-update.yml
--- a/.github/workflows/stage-values-update.yml
+++ b/.github/workflows/stage-values-update.yml
@@ -77,7 +77,7 @@ jobs:
             exit 1
           else
             git diff --staged > ../diff_output.txt
-            cat ../diff_output.txt || echo "Failed to generate diff_output.txt" && exit 1
+            cat ../diff_output.txt || echo "Failed to generate diff_output.txt"
             git commit -m "Update deployment values for stage from ${{ env.UPDATED_FILES }}"
             git push origin main
             if [[ $? -ne 0 ]]; then
