fixing the logic.

diff --git a/.github/workflows/stage-values-update.yml b/.github/workflows/stage-values-update.yml
--- a/.github/workflows/stage-values-update.yml
+++ b/.github/workflows/stage-values-update.yml
@@ -64,16 +64,18 @@ jobs:
           
           git add environments/stage/${{ env.APP_NAME }}/$(basename ${{ env.UPDATED_FILES }})
           if git diff-index --quiet HEAD; then
-          echo "No changes to commit."
-          echo "NO_CHANGES=true" >> $GITHUB_ENV
+            echo "No changes to commit."
+            echo "NO_CHANGES=true" >> $GITHUB_ENV
           else
-          git commit -m "Update deployment values for stage from ${{ env.UPDATED_FILES }}"
-          git push origin main > git_push_output.txt 2>&1 || {
-           echo "PUSH_FAILED=true" >> $GITHUB_ENV
-           echo "Git push failed. See output:" >> git_push_output.txt
-           cat git_push_output.txt
-           exit 1
-          }
+            git commit -m "Update deployment values for stage from ${{ env.UPDATED_FILES }}"
+            git push origin main > git_push_output.txt 2>&1 || {
+            echo "PUSH_FAILED=true" >> $GITHUB_ENV
+            echo "NO_CHANGES=false" >> $GITHUB_ENV
+            echo "PUSH_FAILED=false" >> $GITHUB_ENV
+            echo "Git push failed. See output:" >> git_push_output.txt
+            cat git_push_output.txt
+            exit 1
+           }
           fi
 
       - name: Failure Summary
@@ -93,7 +95,7 @@ jobs:
           fi
 
       - name: Successful Summary
-        if: env.NO_CHANGES == 'false' || env.PUSH_FAILED == 'false'
+        if: env.NO_CHANGES != 'true' && env.PUSH_FAILED != 'true'
         env:
           APP_NAME: ${{ env.APP_NAME }}
           UPDATED_FILES: ${{ env.UPDATED_FILES }}
